# Generated by Django 5.1.1 on 2024-09-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dz_first_app', '0002_alter_category_options_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at', 'status', 'deadline'], 'verbose_name': 'Task'},
        ),
    ]
