# Generated by Django 5.1.1 on 2024-09-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dz_first_app', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at', 'status', 'deadline'], 'verbose_name': 'Task'},
        ),
    ]
