# Generated by Django 5.1.1 on 2024-10-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz_first_app', '0006_alter_task_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(blank=True, to='dz_first_app.category'),
        ),
    ]
