# Generated by Django 5.1.1 on 2024-10-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz_first_app', '0007_alter_task_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default='Now'),
        ),
    ]
